---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-xray-report

---
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  name: kube-xray-report
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods
  verbs:
  - get
  - list

---

apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-xray-report
roleRef:
  name: kube-xray-report
subjects:
- kind: ServiceAccount
  name: kube-xray-report
  namespace: default
